## Pandas-DataFrame and Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures. Series and DataFrame. A Series is a one-dimensional array-like object, while DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pashu\downloads\data-science-machine-learning-deep-learning-and-nlp\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
## Series
## A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## Create a series from dictionary 
data={'a':1,'b':2,'c':3,'d':4}
series=pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [6]:
## To give specific index
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
##DataFrame
## create a dataframe from a dictionary of lisst

data={
    "Name":['Pashupati','Vantika','Abhishek'],
    "Age":[23,5,25],
    "City":["Bikramganj","Arrah","Bikramganj"]
}

df=pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age        City
0  Pashupati   23  Bikramganj
1    Vantika    5       Arrah
2   Abhishek   25  Bikramganj
<class 'pandas.core.frame.DataFrame'>

In [8]:
import numpy as np
np.array(df)

array([['Pashupati', 23, 'Bikramganj'],
       ['Vantika', 5, 'Arrah'],
       ['Abhishek', 25, 'Bikramganj']], dtype=object)

In [9]:
result=0.3+0.6
print(result)

0.8999999999999999

In [10]:
#Create a dataframe from a list of dictionary

data=[
    {"Name":'Pashupati','Age':22,'City':"Bikramganj"},
    {"Name":'Abhishek','Age':24,'City':"Bikramganj"},
    {"Name":'Vantika','Age':5,'City':"Arrah"},
]
df=pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age        City
0  Pashupati   22  Bikramganj
1   Abhishek   24  Bikramganj
2    Vantika    5       Arrah
<class 'pandas.core.frame.DataFrame'>

In [11]:
df=pd.read_csv('online_sales_data_1000.csv')
print(df)

     Transaction ID        Date         Category            Product  Quantity  \
0             10001  2025-10-06           Sports           Yoga Mat         3
1             10002  2026-01-19            Books      Atomic Habits         1
2             10003  2025-05-22         Clothing             Jacket         2
3             10004  2025-04-09  Beauty Products           Lipstick         2
4             10005  2026-02-21         Clothing             Jacket         2
..              ...         ...              ...                ...       ...
995           10996  2025-11-06      Electronics        MacBook Air         4
996           10997  2025-05-05           Sports      Tennis Racket         1
997           10998  2026-03-27  Beauty Products          Face Wash         5
998           10999  2025-06-23            Books  Rich Dad Poor Dad         4
999           11000  2026-03-31            Books      The Alchemist         2

       Price  Revenue         Region Payment Method
0    1404.61  4213.83  South America            UPI
1     356.35   356.35  North America    Net Banking
2     975.48  1950.96           Asia     Debit Card
3     297.55   595.10  North America    Credit Card
4     301.27   602.54         Africa            UPI
..       ...      ...            ...            ...
995  1452.62  5810.48         Africa    Credit Card
996    49.26    49.26  South America    Net Banking
997   288.23  1441.15         Africa    Net Banking
998   667.70  2670.80  South America    Credit Card
999   618.11  1236.22         Africa    Net Banking

[1000 rows x 9 columns]

In [12]:
##To see top 5 record
df.head(5)

,Transaction ID,Date,Category,Product,Quantity,Price,Revenue,Region,Payment Method
0,10001,2025-10-06,Sports,Yoga Mat,3,1404.61,4213.83,South America,UPI
1,10002,2026-01-19,Books,Atomic Habits,1,356.35,356.35,North America,Net Banking
2,10003,2025-05-22,Clothing,Jacket,2,975.48,1950.96,Asia,Debit Card
3,10004,2025-04-09,Beauty Products,Lipstick,2,297.55,595.10,North America,Credit Card
4,10005,2026-02-21,Clothing,Jacket,2,301.27,602.54,Africa,UPI

In [13]:
##To see last 5 record
df.tail(5)

,Transaction ID,Date,Category,Product,Quantity,Price,Revenue,Region,Payment Method
995,10996,2025-11-06,Electronics,MacBook Air,4,1452.62,5810.48,Africa,Credit Card
996,10997,2025-05-05,Sports,Tennis Racket,1,49.26,49.26,South America,Net Banking
997,10998,2026-03-27,Beauty Products,Face Wash,5,288.23,1441.15,Africa,Net Banking
998,10999,2025-06-23,Books,Rich Dad Poor Dad,4,667.70,2670.80,South America,Credit Card
999,11000,2026-03-31,Books,The Alchemist,2,618.11,1236.22,Africa,Net Banking

In [14]:
##Accessing data from dataframe
df

,Transaction ID,Date,Category,Product,Quantity,Price,Revenue,Region,Payment Method
0,10001,2025-10-06,Sports,Yoga Mat,3,1404.61,4213.83,South America,UPI
1,10002,2026-01-19,Books,Atomic Habits,1,356.35,356.35,North America,Net Banking
2,10003,2025-05-22,Clothing,Jacket,2,975.48,1950.96,Asia,Debit Card
3,10004,2025-04-09,Beauty Products,Lipstick,2,297.55,595.10,North America,Credit Card
4,10005,2026-02-21,Clothing,Jacket,2,301.27,602.54,Africa,UPI
...,...,...,...,...,...,...,...,...,...
995,10996,2025-11-06,Electronics,MacBook Air,4,1452.62,5810.48,Africa,Credit Card
996,10997,2025-05-05,Sports,Tennis Racket,1,49.26,49.26,South America,Net Banking
997,10998,2026-03-27,Beauty Products,Face Wash,5,288.23,1441.15,Africa,Net Banking
998,10999,2025-06-23,Books,Rich Dad Poor Dad,4,667.70,2670.80,South America,Credit Card
999,11000,2026-03-31,Books,The Alchemist,2,618.11,1236.22,Africa,Net Banking

In [15]:
df['Category']

0               Sports
1                Books
2             Clothing
3      Beauty Products
4             Clothing
            ...
995        Electronics
996             Sports
997    Beauty Products
998              Books
999              Books
Name: Category, Length: 1000, dtype: object

In [16]:
type(df['Category'])

pandas.core.series.Series

In [17]:
df.loc[0]

Transaction ID            10001
Date                 2025-10-06
Category                 Sports
Product                Yoga Mat
Quantity                      3
Price                   1404.61
Revenue                 4213.83
Region            South America
Payment Method              UPI
Name: 0, dtype: object

In [18]:
df.iloc[0][3]

C:\Users\pashu\AppData\Local\Temp\ipykernel_2164\3304378415.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][3]

'Yoga Mat'

In [81]:
## Creating New DataFrame

import pandas as pd

data={
    "Name" : ["Ram", "Shyam", "Mohan"],
    "Age" : [20, 21, 22],
    "City" : ["Delhi", "Patna", "Bhopal"]
}

df1=pd.DataFrame(data)

In [82]:
df1

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21   Patna
2  Mohan   22  Bhopal

In [83]:
## Accessing a specificied element

df1['Age']

0    20
1    21
2    22
Name: Age, dtype: int64

In [84]:
df1

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21   Patna
2  Mohan   22  Bhopal

In [85]:
## Accessing a specificied element

df1.at[1,'Age'] ##df.at[row index,column index]

np.int64(21)

In [86]:
## Accessing a specificied element

df1.at[0,'Age']

np.int64(20)

In [87]:
## Accessing a specificied element

df1.at[2,'Age']

np.int64(22)

In [88]:
df1

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21   Patna
2  Mohan   22  Bhopal

In [89]:
## Accessing a specified element using iat

## Hera iat means row index and column index

df1.iat[2,2]

'Bhopal'

In [90]:
## Data Manipulation with DataFrame

df1

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21   Patna
2  Mohan   22  Bhopal

In [91]:
## Adding a new column
df1["New City"]=["Kolkata", "Bangalor", "Gujarat"]
df1

    Name  Age    City  New City
0    Ram   20   Delhi   Kolkata
1  Shyam   21   Patna  Bangalor
2  Mohan   22  Bhopal   Gujarat

In [92]:
## Remove a column
## drop is temporary operation
##For permanently remove we have to use inplace =True
df1.drop("New City", axis=1)   ##when axis=0 it check row and when axis=1 it check column
df1

    Name  Age    City  New City
0    Ram   20   Delhi   Kolkata
1  Shyam   21   Patna  Bangalor
2  Mohan   22  Bhopal   Gujarat

In [93]:
## drop is temporary operation
##For permanently remove we have to use inplace =True
df1.drop("New City",axis=1,inplace=True)
df1

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21   Patna
2  Mohan   22  Bhopal

In [94]:
## Add age to the columns
df1['Age']=df1['Age']+1
df1

    Name  Age    City
0    Ram   21   Delhi
1  Shyam   22   Patna
2  Mohan   23  Bhopal

In [95]:
df1.drop(0) ##Drop based on row
##This again not a permanent operation

    Name  Age    City
1  Shyam   22   Patna
2  Mohan   23  Bhopal

In [96]:
df1

    Name  Age    City
0    Ram   21   Delhi
1  Shyam   22   Patna
2  Mohan   23  Bhopal

In [97]:
## Now this permanent Operation
df1.drop(0, inplace=True)

In [79]:
df1

    Name  Age    City
1  Shyam   22   Patna
2  Mohan   23  Bhopal

In [99]:
df2=pd.read_csv('online_sales_data_1000.csv')
df2.head(5)

,Transaction ID,Date,Category,Product,Quantity,Price,Revenue,Region,Payment Method
0,10001,2025-10-06,Sports,Yoga Mat,3,1404.61,4213.83,South America,UPI
1,10002,2026-01-19,Books,Atomic Habits,1,356.35,356.35,North America,Net Banking
2,10003,2025-05-22,Clothing,Jacket,2,975.48,1950.96,Asia,Debit Card
3,10004,2025-04-09,Beauty Products,Lipstick,2,297.55,595.10,North America,Credit Card
4,10005,2026-02-21,Clothing,Jacket,2,301.27,602.54,Africa,UPI